# Redes neuronales con Pytorch

@jivg.org

## Introducción

¡Bienvenidos a esta serie de prácticas diseñadas para aprender PyTorch, uno de los frameworks más potentes y flexibles para el desarrollo de proyectos en aprendizaje profundo!

PyTorch ha ganado popularidad por su enfoque intuitivo, su integración con Python y su soporte para la creación de modelos complejos de redes neuronales. Este conjunto de prácticas te guiará desde los conceptos básicos hasta la implementación de redes neuronales avanzadas, brindándote las herramientas necesarias para abordar problemas reales en el mundo del aprendizaje automático.


[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/irvingvasquez/practicas_pytorch/blob/master/01_Intro_redes_y_tensores.ipynb)

## Tensores en Pytorch

Los tensores son una generalización de los vectores y matrices. Cuando hablamos de un tensor de una dimensión nos estamos refierendo a un vector que puede tener $n$ elementos. Podemos tener tensores de varias dimensiones, por ejemplo una matriz 2D sería un tensor 2D y así sucesivamente. Los tensores son la base de muchos paquetes de para programar deep learning, debido a que las redes neuronales son ¡un montón de operaciones matriciales!, además mantienen la conección en el grafo y permiten la implementación del gradiente descendiente. Asi que es indispensable tener una representación adecuada para reducir el tiempo de entrenamiento. 

Sin más preámbulo vayamos a la programación.

In [1]:
# Primero importemos los paquetes necesarios

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
print(np.__version__)
import torch
print(torch.__version__)

1.26.4
1.12.0


### Construcción

Comenzemos por explorar el uso de tensores. Algunas funciones básias para construir los tensores son:

**`torch.tensor`**:
   - Esta función se usa para crear un tensor directamente a partir de datos. Ejemplo de uso:
      ```python
      data = [[1, 2], [3, 4]]
      tensor = torch.tensor(data)
      ```

 **`torch.ones`**:
   - Crea un tensor lleno de unos con las dimensiones especificadas. Ejemplo de uso:
      ```python
      tensor = torch.ones(2, 4)  # Crea un tensor 2x4 lleno de unos
      ```

**`torch.arange`**:
   - Genera un tensor con valores en un rango especificado con un paso determinado. Ejemplo de uso:
      ```python
      tensor = torch.arange(0, 10, 2)  # Crea un tensor con valores [0, 2, 4, 6, 8]
      ```

**`torch.randn`**:
   - Genera un tensor con valores aleatorios distribuidos normalmente (media 0, desviación estándar 1). Ejemplo de uso:
      ```python
      tensor = torch.randn(3, 3)  # Crea un tensor 3x3 con valores aleatorios de una distribución normal
      ```

In [2]:
# Tensor de 4 por 2 elementos relleno de unos
y = torch.ones(4,2)
# Tensor de 3 por 3 elementos relleno de valores aleatorios
r = torch.randn(3,3)

print(y)
print(r)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[ 1.1353, -0.6624, -1.1494],
        [ 0.2382,  0.2050,  0.3718],
        [ 1.5074, -0.1585,  1.0304]])


En PyTorch, puedes realizar una amplia variedad de operaciones básicas con tensores. A continuación veremos algunas de las operaciones más comunes:

- Adición. Se usa el operador `+`
- Sustracción. Se usa el operador `-`
- Multiplicación elemento por elemento. Operador `*`
- División elemento por elemento. Operador `/`
- Exponenciación. Operador `**`


In [3]:
# Operaciónes entre tensores
# suma de tensores
z = y + y + y
print("Suma:", z)

# resta de tensores
z = z - y
print("Resta:", z)

Suma: tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])
Resta: tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])


Acceder a los elementos de un tensor en PyTorch es muy similar a cómo se accede a los elementos en una lista o un arreglo de NumPy.

In [4]:
# acceder a un elemento del tensor
print(z[1][1])

# acceder a la segunda fila
print(z[1])

# acceder a la segunda columna
print(z[:,1])

tensor(2.)
tensor([2., 2.])
tensor([2., 2., 2., 2.])


In [5]:
# Observa el siguiete código y trata de entender que hace
z[:,1:]

tensor([[2.],
        [2.],
        [2.],
        [2.]])

La notación z[:, 1:] en PyTorch se utiliza para seleccionar una porción específica de un tensor. Aquí está el desglose:
- : indica que se seleccionan todas las filas del tensor.
- 1: indica que se seleccionan todas las columnas desde la segunda columna en adelante (recordando que los índices en Python son cero-basados).
Por lo tanto, z[:, 1:] selecciona todas las filas y todas las columnas desde la segunda columna hasta el final

### Reshape

Una de las cosas más comunes que realizaŕas con los tensores es consultar su 'forma' es decir, la cantidad de elementos que hay en él, para tal función existe *.size()* 

Si deseamos cambiar la forma del tensor entonces utilizaremos *.resize_()* Observa que el guión bajo indica que se va a modificar el tensor en sí, si no utilizamos el guión bajo se creará un nuevo tensor.

In [6]:
z.size()

torch.Size([4, 2])

In [7]:
z.resize_(3,3)

tensor([[2.0000e+00, 2.0000e+00, 2.0000e+00],
        [2.0000e+00, 2.0000e+00, 2.0000e+00],
        [2.0000e+00, 2.0000e+00, 1.0378e-38]])

### Pasando Tensores a Numpy

Antes de hacer el entrenamiento de una red es muy probable que tengamos que hacer un preprocesamiento de los datos. Usualmente, el procesamiento se hace en numpy por facilidad además que tenemos muchísimas herramientas disponibles. Afortunadamente, pytorch provee una funciones para poder convertir entre formatos de forma casi directa. Para convetir de numpy a tensor usamos *torch.from_numpy()* y para retornar de torch a numpy utilizamos el método *.numpy()*

In [8]:
# generemos un array en numpy
a = np.random.rand(4,3)
print(a)


[[0.88287308 0.16807635 0.31020138]
 [0.91777182 0.40180744 0.70725716]
 [0.54134548 0.91257211 0.25928722]
 [0.15786873 0.57274718 0.6367663 ]]


In [9]:
# convertir a pytorch
A = torch.from_numpy(a)
print(A)

tensor([[0.8829, 0.1681, 0.3102],
        [0.9178, 0.4018, 0.7073],
        [0.5413, 0.9126, 0.2593],
        [0.1579, 0.5727, 0.6368]], dtype=torch.float64)


In [10]:
# convertir a numpy
b = A.numpy()
print(b)

[[0.88287308 0.16807635 0.31020138]
 [0.91777182 0.40180744 0.70725716]
 [0.54134548 0.91257211 0.25928722]
 [0.15786873 0.57274718 0.6367663 ]]


Advertencia! Ten cuidado por que resulta que las variables convertidas de pytorch a numpy comparte memoria asi que si modificas uno se modificará el otro!

In [11]:
print(A)

tensor([[0.8829, 0.1681, 0.3102],
        [0.9178, 0.4018, 0.7073],
        [0.5413, 0.9126, 0.2593],
        [0.1579, 0.5727, 0.6368]], dtype=torch.float64)


In [12]:
# multipliquemos el tensor
A.mul_(2)
print(A)

tensor([[1.7657, 0.3362, 0.6204],
        [1.8355, 0.8036, 1.4145],
        [1.0827, 1.8251, 0.5186],
        [0.3157, 1.1455, 1.2735]], dtype=torch.float64)


ahora observemos el array

In [13]:
a

array([[1.76574615, 0.33615271, 0.62040276],
       [1.83554364, 0.80361487, 1.41451433],
       [1.08269096, 1.82514422, 0.51857444],
       [0.31573746, 1.14549436, 1.2735326 ]])

### Funciones básicas

PyTorch proporciona una serie de funciones básicas para realizar operaciones aritméticas y de manipulación de tensores.

- **`torch.add`**:
   - Suma dos tensores elemento por elemento. Uso:
      ```python
      a = torch.tensor([1, 2, 3])
      b = torch.tensor([4, 5, 6])
      c = torch.add(a, b)  # c = [5, 7, 9]
      ```
- **`torch.sub`**:
   - Resta dos tensores elemento por elemento.
      ```python
      c = torch.sub(a, b)  # c = [-3, -3, -3]
      ```
- **`torch.dot`:**
   - Realiza el producto punto de dos vectores.
      ```python
      c = torch.dot(a, b) 
      ```


In [15]:
# Implementa un perceptrón
x_np = np.array([2.0, 3.0, 4.0])
w_np = np.array([0.1, 0.1, 0.2])
b_np = np.array([1.0])

# Convierte los vectores a tensores de pytorch
X = torch.from_numpy(x_np)
print(X)
W = torch.from_numpy(w_np)
print(W)
B = torch.from_numpy(b_np)
print(B)

tensor([2., 3., 4.], dtype=torch.float64)
tensor([0.1000, 0.1000, 0.2000], dtype=torch.float64)
tensor([1.], dtype=torch.float64)


## Implementando el perceptrón

<img src="archivos/simple_neuron.png" width=400>
Imagen tomada de [Udacity]

Podemos ver la salida del perceptrón como una secuencia de operaciones, primero se calcula $h$ a partir del producto punto, entre las entradas $X$ y los pesos $W$, sumado a el sesgo $b$, es decir

$$h = MX + b$$

despúes se 'pasa' $h$ por una función de activación que transforma el valor,

$$y = f(h)$$

In [16]:
# realiza las operaciones necesarias y calcula la combinación lineal h
# algunas funciones útiles son torch.add() y torch.dot()
# y = W*X + B
H =  torch.add(torch.dot(W,X),B)
print(H)


tensor([2.3000], dtype=torch.float64)


In [18]:
# Pasa h por la función de activación segmoide torch.sigmoid()
Y = torch.tanh(H)
print(Y)

tensor([0.9801], dtype=torch.float64)


In [19]:
# Finalmente regresamos el tensor a un array de numpy
y_np = Y.numpy()
print(y_np)

[0.9800964]
