# Introducción

## Redes Neuronales

Las redes neuronales son un modelo matemático que nos permite aproximar una función. Tienen similitud a las neuronas del cerebro en el sentido que ambas reciben varias entradas, realizan un cálculo y determinan una salida la cual es entrada para otras neuronas. 

En la siguiente imagen encontrarás una neurona simple, también conocida como perceptrón.

<img src="archivos/simple_neuron.png">
Imagen tomada de [Udacity]


Podemos ver la salida del perceptrón como una secuencia de operaciones, primero se calcula $h$ a partir del producto punto, entre las entradas $X$ y los pesos $W$, sumado a el sesgo $b$, es decir

$$h = MX + b$$

despúes se 'pasa' $h$ por una función de activación que transforma el valor,

$$y = f(h)$$






## Tensores en Pytorch

Los tensores son una generalicación de los vectores y matrices. Cuando hablamos de un tensor de una dimensión nos estamos refierendo a un vector que puede tener n elementos. Podemos tener tensores de varias dimensiones, por ejemplo una matriz 2D sería un tensor 2D y así sucesivamente. Los tensores son la base de muchos paquetes de para programar deep learning, debido a que las redes neuronales son ¡un montón de operaciones matriciales!. Asi que es indispensable tener una representación adecuada. 

Sin más preámbulo vayamos a la programación.

In [1]:
# Primero importemos los paquetes necesarios

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import torch


Comenzemos a explorar los tensores. Creemos unos tensores y realizemos algunas opereaciones entre ellos.

In [2]:
# Tensor de 4 por 2 elementos relleno de unos
y = torch.ones(4,2)
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [3]:
# operación entre tensores
z = y + y
z

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])

In [4]:
# acceder a los elementos de un tensor
z[1][1]

tensor(2.)

In [5]:
z[:,1:]

tensor([[2.],
        [2.],
        [2.],
        [2.]])

### Reshape

Una de las cosas más comunes que realizaŕas con los tensores es consultar su 'forma' es decir, la cantidad de elementos que hay en él, para tal función existe *.size()* 

Si deseamos cambiar la forma del tensor entonces utilizaremos *.resize_()* Observa que el guión bajo indica que se va a modificar el tensor en sí, si no utilizamos el guión bajo se creará un nuevo tensor.

In [6]:
z.size()

torch.Size([4, 2])

In [7]:
z.resize_(2,4)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])

### Pasando Tensores a Numpy

Antes de hacer el entrenamiento de una red es muy probable que tengamos que hacer un preprocesamiento de los datos. Usualmente, el procesamiento se hace en numpy por facilidad además que tenemos muchísimas herramientas disponibles. Afortunadamente, pytorch provee una funciones para poder convertir entre formatos de forma casi directa. Para convetir de numpy a tensor usamos *torch.from_numpy()* y para retornar de torch a numpy utilizamos el método *.numpy()*

In [8]:
# generemos un array en numpy
a = np.random.rand(4,3)
a

array([[ 0.20273743,  0.97233966,  0.45164884],
       [ 0.8474777 ,  0.75065332,  0.58210348],
       [ 0.46748066,  0.73797552,  0.71817105],
       [ 0.35484526,  0.93628444,  0.96990226]])

In [9]:
# convertir a pytorch
A = torch.from_numpy(a)
A

tensor([[0.2027, 0.9723, 0.4516],
        [0.8475, 0.7507, 0.5821],
        [0.4675, 0.7380, 0.7182],
        [0.3548, 0.9363, 0.9699]], dtype=torch.float64)

In [10]:
# convertir a numpy
b = A.numpy()

Advertencia! Ten cuidado por que resulta que las variables convertidas de pytorch a numpy comparte memoria asi que si modificas uno se modificará el otro!

In [11]:
# multipliquemos el tensor
A.mul_(2)

tensor([[0.4055, 1.9447, 0.9033],
        [1.6950, 1.5013, 1.1642],
        [0.9350, 1.4760, 1.4363],
        [0.7097, 1.8726, 1.9398]], dtype=torch.float64)

ahora observemos el array

In [12]:
a

array([[ 0.40547487,  1.94467933,  0.90329767],
       [ 1.69495541,  1.50130663,  1.16420696],
       [ 0.93496132,  1.47595104,  1.43634209],
       [ 0.70969052,  1.87256888,  1.93980452]])

### Perceptrón

Ejercicio: implementa un perceptrón utilizando funciones de PyTorch

In [29]:
# Implementa un perceptrón
x_np = np.array([2.0, 3.0, 4.0])
w_np = np.array([0.1, 0.1, 0.2])
b_np = np.array([1.0])

# en numpy seria
h_np = None
print(h_np)

# Convierte los vectores a tensores de pytorch
X = None
W = None
B = None
# realiza las operaciones necesarias y calcula la combinación lineal h
# algunas funciones útiles son torch.add() y torch.dot()
H = None

# Pasa h por la función de activación segmoide torch.sigmoid()
Y = None

[ 2.3]
tensor([2, 3, 4])
tensor([0.1000, 0.1000, 0.2000], dtype=torch.float64)


tensor([0.9089], dtype=torch.float64)

tensor(14.)